apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: helloworld
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: helloworld
    app.kubernetes.io/part-of: shebert-app
  name: helloworld
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: helloworld
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: helloworld
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/shebert-tenant/shebert-app/helloworld@sha256:1e2d1415c5c71d1051b6a60bc611837306f8b2e1568646f2e484875bd54a869f
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
